version: '3'

services:
  jenkins: 
    build: .
      
      
    # To disable the security labeling for this container
    privileged: true

    # Container User if required
    user: root
    
    # choose container name 
    container_name: jenkins-casc

    # Listen on the desired ports
    # - Port 8080   exposes the web interface
    # - Port 50000  gives you access to a remote Java (Jenkins) API.
    ports: 
      - 8080:8080
      - 50000:50000
      
    # the mount volumes
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    # Skip the setup wizard
    environment:
      - jenkins.install.runSetupWizard=false

volumes:
  jenkins_home: